/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2019-03-06 14:10:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link href=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Knowledge Graph</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        *\r\n");
      out.write("        {\r\n");
      out.write("            margin:0px;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("        }\r\n");
      out.write("        ul.navbar \r\n");
      out.write("        {\r\n");
      out.write("            background:#4a7746;\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .navbar > li > a i\r\n");
      out.write("        {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar > li > a:hover,.navbar > li.active > a\r\n");
      out.write("        {\r\n");
      out.write("            background: #335230;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar > li > a\r\n");
      out.write("        {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .brand\r\n");
      out.write("        {\r\n");
      out.write("            background: #3e523d;\r\n");
      out.write("            color:#fff;\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            padding:18px 10px; \r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .brand a:hover\r\n");
      out.write("        {\r\n");
      out.write("            background: #444;\r\n");
      out.write("        }\r\n");
      out.write("        .brand a i\r\n");
      out.write("        {\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .brand a\r\n");
      out.write("        {\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            background: #4a7746;\r\n");
      out.write("        }\r\n");
      out.write("        .hideNav\r\n");
      out.write("        {\r\n");
      out.write("           \r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        @media screen and (min-width: 768px) {\r\n");
      out.write("           \r\n");
      out.write("            ul.navbar {\r\n");
      out.write("               height: 100vh;\r\n");
      out.write("                width: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar li span\r\n");
      out.write("            {\r\n");
      out.write("                visibility: hidden;\r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar li a i\r\n");
      out.write("            {\r\n");
      out.write("                font-size: 30px;\r\n");
      out.write("                padding-top: 22px;\r\n");
      out.write("                \r\n");
      out.write("                vertical-align: middle;\r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar li\r\n");
      out.write("            {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .btn-bars\r\n");
      out.write("            {\r\n");
      out.write("                visibility: visible;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("         @media screen and (min-width: 768px) {\r\n");
      out.write("            .brand\r\n");
      out.write("            {\r\n");
      out.write("                padding-right: 10px;\r\n");
      out.write("                background: #3e523d;\r\n");
      out.write("                color:#fff;\r\n");
      out.write("                width: 16.666%;\r\n");
      out.write("             }\r\n");
      out.write("            \r\n");
      out.write("            ul.navbar {\r\n");
      out.write("                width: 16.666%;\r\n");
      out.write("            }\r\n");
      out.write("               ul.navbar.hideNav\r\n");
      out.write("             {\r\n");
      out.write("                width: 100px;\r\n");
      out.write("                visibility: visible;\r\n");
      out.write("             }\r\n");
      out.write("              ul.navbar.hideNav {\r\n");
      out.write("               height: 100vh;\r\n");
      out.write("                width: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar.hideNav li span\r\n");
      out.write("            {\r\n");
      out.write("                visibility: hidden;\r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar.hideNav li a i\r\n");
      out.write("            {\r\n");
      out.write("                font-size: 30px;\r\n");
      out.write("                padding-top: 22px;\r\n");
      out.write("                \r\n");
      out.write("                vertical-align: middle;\r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar.hideNav li\r\n");
      out.write("            {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("           \r\n");
      out.write("            ul.navbar.hideNav li span\r\n");
      out.write("            {\r\n");
      out.write("                text-align: left;\r\n");
      out.write("                visibility: visible;\r\n");
      out.write("            }\r\n");
      out.write("             ul.navbar li span\r\n");
      out.write("            {\r\n");
      out.write("                text-align: left;\r\n");
      out.write("                visibility: visible;\r\n");
      out.write("            }\r\n");
      out.write("              ul.navbar li a i\r\n");
      out.write("            {\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("                padding-top: 0px;\r\n");
      out.write("                vertical-align: baseline;\r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar li a \r\n");
      out.write("            {\r\n");
      out.write("                padding-top: 22px;\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("            ul.navbar li\r\n");
      out.write("            {\r\n");
      out.write("                text-align: left;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        .header\r\n");
      out.write("        {\r\n");
      out.write("            height: 70.48px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: #163c12;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right ul\r\n");
      out.write("        {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            margin: 0px;padding:0px;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right\r\n");
      out.write("        {\r\n");
      out.write("            width: 83.3333%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right input\r\n");
      out.write("        {\r\n");
      out.write("            margin: 15px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            border-radius:5px;\r\n");
      out.write("            border:0px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header-right ul.navbar-right\r\n");
      out.write("        {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            top: 60px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            box-shadow: 0px 0px 3px 1px #ddd;\r\n");
      out.write("            width:200px;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right ul.navbar-right li.active,\r\n");
      out.write("        .header-right ul.navbar-right li:hover\r\n");
      out.write("        {\r\n");
      out.write("            \r\n");
      out.write("            background: #f4f4f4;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right ul.navbar-right li a i\r\n");
      out.write("        {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right ul.navbar-right li a\r\n");
      out.write("        {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 10px 10px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .blog-user\r\n");
      out.write("        {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("        .blog-user a.avator img \r\n");
      out.write("        {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("        .avator \r\n");
      out.write("        {   \r\n");
      out.write("            height: 55px;\r\n");
      out.write("            width: 55px;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .avator img\r\n");
      out.write("        {\r\n");
      out.write("            border-radius: 100px;\r\n");
      out.write("           height: 90%;\r\n");
      out.write("            border:4px solid #fff; \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header-right ul.navbar-right li\r\n");
      out.write("        {\r\n");
      out.write("            z-index: 9999;            \r\n");
      out.write("            border-bottom: 1px solid #e1e1e1;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .hidden\r\n");
      out.write("        {\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <body>\r\n");
      out.write("        <script>\r\n");
      out.write("            $(function(){\r\n");
      out.write("                $(\".btn-bars\").click(function(){\r\n");
      out.write("                    $(\".navbar\").toggleClass(\"hideNav\",\"slow\");\r\n");
      out.write("                });\r\n");
      out.write("                $(\".avator\").click(function(){\r\n");
      out.write("                    $(\".navbar-right\").toggleClass(\"hidden\",\"slow\");\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("        <nav class=\"nav-bar\">\r\n");
      out.write("            <div class=\"header\">\r\n");
      out.write("                     <div class=\"brand\"> Knowledge Graph    <a href=\"javascript:void(0)\" class=\"btn-bars\"> <i class=\"fa fa-bars\"></i></a></div>\r\n");
      out.write("                \r\n");
      out.write("                     <div class=\"header-right\"> \r\n");
      out.write("                        <input type=\"search\">\r\n");
      out.write("                         <div class=\"blog-user\">\r\n");
      out.write("                            <a href=\"#\" class=\"avator\"><img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgV1cokAhUc_f0ljJt88_Jf4K9RaRgZSvGuUCBV6Up4SS9wo--\"></a>\r\n");
      out.write("                         \r\n");
      out.write("                          <ul class=\"navbar-right hidden\">\r\n");
      out.write("                                \r\n");
      out.write("                                <li><a href=\"index.jsp\"><i class=\"fa fa-home\"></i><span>Log Out</span></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("              </div>\r\n");
      out.write("            <ul class=\"navbar\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-user\"></i><span>Home </span></a></li>\r\n");
      out.write("                <li><a href=\"facaltyreg.jsp\"><i class=\"fa fa-map\"></i><span>faculty Register</span> </a></li>\r\n");
      out.write("                                <li><a href=\"assign.jsp\"><i class=\"fa fa-sliders\"></i><span>Assign Subject </span></a></li>\r\n");
      out.write("                                <li><a href=\"editreg.jsp\"><i class=\"fa fa-edit\"></i><span>Edit Regiter</span></a></li>\r\n");
      out.write("                                <li><a href=\"addsub.jsp\"><i class=\"fa fa-map\"></i><span>Add Subject</span> </a></li>                               \r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-edit\"></i><span>Edit Subject Detail</span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
